gui:
  theme:
    activeBorderColor:
      - '#FF9E64'
      - bold
    selectedLineBgColor:
      - '#D55000'
      - bold
git:
  parseEmoji: true
  overrideGpg: true
os:
  editPreset: 'nvim'
  editCommand: 'nvim'
keybinding:
  commits:
    g: <disabled>
  commitGraph:
    g: <disabled>
